#!/bin/bash

#Enter the update package file name: e.g., aosp_hammerhead-img-eng.adwait.zip
#The update file is generated by building as: make updatepackage
updatepackage="";

# Option 1: flash updatepackage
function flash_updatepackage
{
	fastboot update aosp_hammerhead-img-eng.adwait.zip
}
# Option 2: flash images
function flash_images
{	
	fastboot flash system system.img
	fastboot flash userdata userdata.img
	fastboot flash boot boot.img
	fastboot reboot
}

if [ "$1" != "" ]; then
	if [ "$1" == "u" ]; then
		flash_updatepackage
	elif [ "$1" == "i" ]; then
		flash_images
	else
		echo "Enter u for update or i for images."
	fi
else
	echo "Enter u for update or i for images."
fi

# Logcat
./display_log.sh
